// DO NOT EDIT. This file is generated by CMake.
// Run CMake configure step to update it.
#include "game/system.h"

#define JULIUS_VERSION "3.0.1"
#define JULIUS_VERSION_SUFFIX "-swiftpm"

const char *system_version(void)
{
    return JULIUS_VERSION JULIUS_VERSION_SUFFIX;
}
